#include <ionlang/const/token_const.h>

namespace ionlang {
    std::map<TokenKind, std::string> TokenConst::names = {
        {TokenKind::Unknown, "Unknown"},
        {TokenKind::Identifier, "Identifier"},
        {TokenKind::LiteralString, "LiteralString"},
        {TokenKind::LiteralDecimal, "LiteralDecimal"},
        {TokenKind::LiteralInteger, "LiteralInt"},
        {TokenKind::LiteralCharacter, "LiteralCharacter"},
        {TokenKind::Whitespace, "Whitespace"},
        {TokenKind::SymbolDollar, "SymbolDollar"},
        {TokenKind::SymbolHash, "SymbolHash"},
        {TokenKind::SymbolParenthesesL, "SymbolParenthesesL"},
        {TokenKind::SymbolParenthesesR, "SymbolParenthesesR"},
        {TokenKind::SymbolBracketL, "SymbolBracketL"},
        {TokenKind::SymbolBracketR, "SymbolBracketR"},
        {TokenKind::SymbolComma, "SymbolComma"},
        {TokenKind::SymbolEqual, "SymbolEqual"},
        {TokenKind::SymbolSemiColon, "SymbolSemiColon"},
        {TokenKind::SymbolStar, "SymbolStar"},
        {TokenKind::SymbolBraceL, "SymbolBraceL"},
        {TokenKind::SymbolBraceR, "SymbolBraceR"},
        {TokenKind::SymbolArrow, "SymbolArrow"},
        {TokenKind::KeywordFunction, "KeywordFunction"},
        {TokenKind::KeywordExtern, "KeywordExtern"},
        {TokenKind::KeywordElse, "KeywordElse"},
        {TokenKind::KeywordGlobal, "KeywordGlobal"},
        {TokenKind::KeywordMutable, "KeywordMutable"},
        {TokenKind::KeywordModule, "KeywordModule"},
        {TokenKind::TypeVoid, "TypeVoid"},
        {TokenKind::TypeString, "TypeString"},
        {TokenKind::TypeInt16, "TypeInt16"},
        {TokenKind::TypeInt32, "TypeInt32"},
        {TokenKind::TypeInt64, "TypeInt64"},
        {TokenKind::OperatorAddition, "OperatorAdd"},
        {TokenKind::OperatorSubtraction, "OperatorSub"},
        {TokenKind::OperatorMultiplication, "OperatorMultiply"},
        {TokenKind::OperatorDivision, "OperatorDivide"},
        {TokenKind::OperatorModulo, "OperatorModulo"},
        {TokenKind::OperatorExponent, "OperatorExponent"},
        {TokenKind::OperatorGreaterThan, "OperatorGreaterThan"},
        {TokenKind::OperatorLessThan, "OperatorLessThan"}
    };
}
